# name: Hello World!

# on:
#   push:
#     branches: [main, master]

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Say hello
#         run: |
#       - name: Now it is
#         run: |
#           echo "Today is $(date)"
#       - name: Another way tto print the date
#         run: |
#           date
#       - name: Directory content
#         run: |
#           ls -l
